import Head from "next/head";
import React, { useState } from "react";
import styles from "../styles/Home.module.css";

export default function Home() {
  const [submittedForm, setSubmittedForm] = useState(false);

  const handleSubmit = async (e) => {
    e.preventDefault();
    const formData = {};
    Array.from(e.currentTarget.elements).forEach((field) => {
      if (!field.name) return;
      formData[field.name] = field.value;
    });

    fetch("/api/mail", {
      method: "post",
      body: JSON.stringify(formData),
    });

    setSubmittedForm(true);
    setTimeout(() => {
      setSubmittedForm(false);
    }, 5000);
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>SendGrid API</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        {submittedForm && (
          <div className={styles.submitted}>
            <h2 className={styles.submitted_text}>Message sent!</h2>
          </div>
        )}
        <h1 className={styles.title}>SendGrid API</h1>
        <div className={styles.grid}>
          <form className={styles.form} method="post" onSubmit={handleSubmit}>
            <label className={styles.label} htmlFor="name">
              Name
            </label>
            <input className={styles.input} type="text" name="name" required />
            <label className={styles.label} htmlFor="email">
              Email
            </label>
            <input
              className={styles.input}
              type="email"
              name="email"
              required
            />
            <label className={styles.label} htmlFor="message">
              Message
            </label>
            <textarea className={styles.input} name="message" />
            <label className={styles.label} htmlFor="datetime">
              Booking Day/Time
            </label>
            <input
              className={styles.input}
              type="datetime-local"
              name="datetime"
              required
            />
            <button className={styles.button}>Submit</button>
          </form>
        </div>
      </main>
    </div>
  );
}
